stages:
  - build
  - deploy

variables:
    PROJECT_NAME: erpweb

build_test_docker:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image: docker:latest
  script:
    - docker build -f Dockerfile -t $PROJECT_NAME .
    - docker tag $PROJECT_NAME git.we2tu.com:5000/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push git.we2tu.com:5000/$PROJECT_NAME:$CI_COMMIT_REF_NAME
  tags:
    - docker
  only:
    - dev

deploy_test_docker:
  stage: deploy
  image: docker:latest
  script: 
    - docker stack deploy -c deploy/deploy.test.yml $PROJECT_NAME
  tags:
    - docker
  only:
    - dev

build_master_docker:
  stage: build
  image: docker:latest
  script:
    - docker build -f Dockerfile -t $PROJECT_NAME .
    - docker tag $PROJECT_NAME git.we2tu.com:5000/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker tag $PROJECT_NAME git.we2tu.com:5000/$PROJECT_NAME:latest
    - docker push git.we2tu.com:5000/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push git.we2tu.com:5000/$PROJECT_NAME:latest
  tags:
    - docker
  only:
    - /^release-.*$/

deploy_prod_docker:
  stage: deploy
  image: docker:latest
  script: 
    - docker stack deploy -c deploy/deploy.prod.yml $PROJECT_NAME
  tags:
    - erp
  only:
    - /^release-.*$/