version: '3'  
services:  
  erpweb:
    image: git.we2tu.com:5000/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    environment:
      - "NODE_ENV=test"
      - "PROJECTNAME=erpweb"
      - "TZ=Asia/Shanghai"
    ports: 
      - 3500:8080
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://172.19.9.13:5514"
        tag: $PROJECT_NAME
    deploy: 
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure